import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFileChooser;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author enesb21
 */
public class see extends javax.swing.JFrame {

    /**
     * Creates new form see
     */
    public see() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    File phac;
    String d[];
    File[] ad;

    static String sss(File s) throws IOException {
        Path f = s.toPath();
        SimpleDateFormat sf = new SimpleDateFormat("MM:dd:HH:mm:ss");
        BasicFileAttributes attr = Files.readAttributes(f, BasicFileAttributes.class);
        String d = sf.format(attr.creationTime().toMillis());
        return d;
    }

    static int[] tarc(File a[]) throws IOException {
        int[] ii = new int[a.length];
        for (int i = 0; i < a.length; i++) {
            String s[] = sss(a[i]).split(":");
            String ss = "";
            for (int j = 0; j < s.length; j++) {
                ss += s[j];
            }
            ii[i] = Integer.parseInt(ss);
        }

        return ii;
    }

    static int[] tarm(File a[]) {
        SimpleDateFormat sdf = new SimpleDateFormat("MMddHHmmss");
        int[] ii = new int[a.length];
        for (int i = 0; i < a.length; i++) {
            ii[i] = Integer.parseInt(sdf.format(a[i].lastModified()));
        }
        return ii;
    }

    void sıralama() throws IOException {
        int[] fg = null;
        if (data1.isSelected()) {
            fg = tarc(ad);
        } else if (data2.isSelected()) {
            fg = tarm(ad);
        }

        for (int i = 0; i < ad.length - 1; i++) {
            int minind = i;
            for (int j = i + 1; j < ad.length; j++) {
                if (fg[j] < fg[minind]) {
                    minind = j;
                }
            }
            if (minind != i) {
                File ara = ad[minind];
                String ara1 = d[minind];
                int ara2 = fg[minind];
                ad[minind] = ad[i];
                d[minind] = d[i];
                fg[minind] = fg[i];
                ad[i] = ara;
                d[i] = ara1;
                fg[i] = ara2;
            }
        }

        list.setListData(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up = new javax.swing.JButton();
        down = new javax.swing.JButton();
        fe = new javax.swing.JButton();
        pres = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        sel = new javax.swing.JComboBox<>();
        data1 = new javax.swing.JCheckBox();
        data2 = new javax.swing.JCheckBox();
        example = new javax.swing.JButton();
        make = new javax.swing.JButton();
        na = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        up.setText("YUKARI");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });

        down.setText("AŞAĞI");
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });

        fe.setText("DOSYA");
        fe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list);

        sel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".mp4", ".txt", ".pdf" }));

        data1.setText("OLUŞTURMA");
        data1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data1ActionPerformed(evt);
            }
        });

        data2.setText("DEGİŞTİRME");
        data2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data2ActionPerformed(evt);
            }
        });

        example.setText("ÖRNEK");
        example.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exampleActionPerformed(evt);
            }
        });

        make.setText("YAP");
        make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(up))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(down)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(data2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(data1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                            .addComponent(sel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pres, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(example)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(make)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fe)
                    .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(data1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data2)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(down)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fe))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(example)
                    .addComponent(make))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feActionPerformed
        // dosya seçimi ve işlemesi
        JFileChooser jfc = new JFileChooser(".");
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.showOpenDialog(null);
        phac = jfc.getSelectedFile();
        String s[] = phac.list();
        d = s;
        ad = phac.listFiles();
        list.setListData(d);
    }//GEN-LAST:event_feActionPerformed

    private void data1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data1ActionPerformed
        // oluşturma tariğine göre sıralıyor
        if (data1.isSelected()) {
            data2.setSelected(false);
            try {
                sıralama();
            } catch (IOException ex) {
                Logger.getLogger(see.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_data1ActionPerformed

    private void data2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data2ActionPerformed
        // deyiştirme tarihine göre sıralıyor
        if (data2.isSelected()) {
            data1.setSelected(false);
            try {
                sıralama();
            } catch (IOException ex) {
                Logger.getLogger(see.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_data2ActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // seçimleri yukarı taşır
        int[] sin = list.getSelectedIndices();
        int i = 0;
        for (String j : list.getSelectedValuesList()) {
            if (j != null) {
                if (sin[i] > 0) {
                    File j1 = ad[sin[i]];
                    String temp = d[sin[i] - 1];
                    File temp1 = ad[sin[i] - 1];
                    d[sin[i] - 1] = j;
                    ad[sin[i] - 1] = j1;
                    d[sin[i]] = temp;
                    ad[sin[i]] = temp1;
                    list.setListData(d);
                    list.setSelectedIndex(sin[i] - 1);
                }
            }
            sin[i]--;
            i++;
        }
        list.setSelectedIndices(sin);
    }//GEN-LAST:event_upActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        //seçimleri aşağı haraket ettirir
        int[] sin = list.getSelectedIndices();
        int i = sin.length - 1;
        List<String> düzd = list.getSelectedValuesList();
        String[] ters = new String[düzd.size()];
        düzd.toArray(ters);
        for (int q = ters.length - 1; q >= 0; q--) {
            if (ters[q] != null) {
                if (sin[i] < d.length - 1) {
                    File j1 = ad[sin[i]];
                    String temp = d[sin[i] + 1];
                    File temp1 = ad[sin[i] + 1];
                    d[sin[i] + 1] = ters[q];
                    ad[sin[i] + 1] = j1;
                    d[sin[i]] = temp;
                    ad[sin[i]] = temp1;
                    list.setListData(d);
                    list.setSelectedIndex(sin[i] + 1);
                }
            }
            sin[i]++;
            i--;
        }
        list.setSelectedIndices(sin);
    }//GEN-LAST:event_downActionPerformed

    private void exampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exampleActionPerformed
        // örneyi gösteriyor
        String a = na.getText();
        a = a + " 1" + sel.getSelectedItem();
        pres.setText(a);
    }//GEN-LAST:event_exampleActionPerformed

    private void makeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeActionPerformed
        // enson hali isme göre uyguluyor
        for (int i = 0; i < ad.length; i++) {
            File es = ad[i];
            File ye = new File(phac.toString() + "\\" + na.getText() + " " + (i + 1) + sel.getSelectedItem());
            boolean a = es.renameTo(ye);
            System.out.println(a);
    }//GEN-LAST:event_makeActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(new FlatArcDarkOrangeIJTheme());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new see().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox data1;
    private javax.swing.JCheckBox data2;
    private javax.swing.JButton down;
    private javax.swing.JButton example;
    private javax.swing.JButton fe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JButton make;
    private javax.swing.JTextField na;
    private javax.swing.JLabel pres;
    private javax.swing.JComboBox<String> sel;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
